version: "3.8"
services:
  db:
    container_name: db
    image: postgres:alpine3.14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "./api/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
  mobile:
    build: ./mobile
    volumes:
      - apk:/dist
  front:
    build:
      context: ./web-app
      dockerfile: Dockerfile
      args:
        - API_ROUTE=/api
        - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
        - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
        - TWITTER_API_KEY=${TWITTER_API_KEY}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
    ports:
      - "8081:80"
    depends_on:
      - "mobile"
    volumes:
      - apk:/dist
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - WORKER_API_KEY=${WORKER_API_KEY}
      - WORKER_URL=${WORKER_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_SECRET=${DISCORD_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
      - TWITTER_SECRET=${TWITTER_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
  worker:
    build: ./worker
    ports:
      - "3001:8999"
    depends_on:
      - "api"
    environment:
      - YOUTUBE_KEY=${YOUTUBE_KEY}
      - WORKER_API_URL=${WORKER_API_URL}
      - WORKER_API_KEY=${WORKER_API_KEY}

volumes:
  apk:

