name:                Aeris-aeris-back
version:             0.1.0.0
github:              "AnonymusRaccoon/Aeris"
license:             BSD3
author:              "Anonymus Raccoon"
maintainer:          "example@example.com"
copyright:           "2022 AnonymusRaccoon/Aeris"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AnonymusRaccoon/aeris/back#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  aeris-back-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeris-back

tests:
  aeris-back-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeris-back
