name:                aeris
version:             0.1.0.0
github:              "AnonymusRaccoon/aeris"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aeris#readme>

dependencies:
- base >= 4.7 && < 5
- opaleye >= 0.9.0.0 && < 0.9.1.0
- aeson == 1.5.6.0
- servant
- servant-server
- servant-auth
- servant-auth-server
- wai
- containers
- warp
- time
- servant-errors
- data-default
- bytestring
- network
- base64
- text
- hasql
- hasql-transaction
- hasql-migration
- hasql-pool
- rel8
- cryptonite
- memory
- transformers
- mr-env
- unordered-containers
- http-media
- http-conduit
- utf8-string

library:
  source-dirs: src

executables:
  aeris-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - aeris

tests:
  aeris-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - aeris
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
