on: [push, pull_request, workflow_dispatch]
name: test

jobs:
  test:
    name: test api
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
      - run: cd api && stack test
