on: [push, pull_request]
name: build

jobs:
  runhaskell:
    name: Hello World
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
      - run: stack test
