name: Documentation deployment
on:
  push:
    branches:
      - master
      - workflows
jobs:
  DeployBackDocumentation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install stack
        run: curl -sSL https://get.haskellstack.org/ | sh -s - -f
      - name: Generate Haddock documentation
        run: stack haddock --haddock-arguments --odir="docs"
      - name: Deploy
        run: |
          cd docs
          git config --global user.email "${GITHUB_ACTOR}@github.com";
          git config --global user.name "${GITHUB_ACTOR}";
          git init
          git add -A;
          git commit -m "Deploying the documentation";
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@${GITHUB_REPO};
          git checkout -b documentation-back
          git push --force origin documentation-back;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: "github.com/AnonymusRaccoon/Aeris"