name: Release

on:
  create:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
  push:
    branches:
      - mobile_client_workflows

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait for builds & tests to finish
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{github.ref}}
          repo-token: ${{secrets.GITHUB_TOKEN}}
          running-workflow-name: release
          allowed-conclusions: success,skipped,cancelled,neutral
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          commit: ${{env.COMMIT_SHA}}
          workflow: build.yml
          github_token: ${{secrets.GITHUB_TOKEN}}
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Mobile APK
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
          artifacts: ./aeris.apk